# Generated by Django 4.1.2 on 2024-04-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_student_student_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stock_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='monthly_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='student_fee',
            field=models.IntegerField(),
        ),
    ]
