# Generated by Django 4.1.2 on 2024-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_monthlypricing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
    ]
