# Generated by Django 4.1.2 on 2024-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_trainer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
