# Generated by Django 4.1.2 on 2024-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_trainer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='payment',
        ),
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
