# Generated by Django 4.1.2 on 2024-04-24 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_barsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='barsold',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
