# Generated by Django 4.1.2 on 2024-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_tariffs_remove_student_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffs',
            name='type',
            field=models.CharField(choices=[('Günlük', 'Günlük'), ('Aylıq', 'Aylıq')], max_length=10),
        ),
    ]
