# Generated by Django 4.1.2 on 2024-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_alter_tariffs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
